record_store/config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
get "/records" => "records#index", as: 'records'
get "/records/new" => "records#new", as: 'new_record'
get "/records/:id" => "records#show", as: 'record'
post "/records" => "records#create"
end

record_store/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

record_store/app/models/record.rb
class Record < ApplicationRecord
end

record_store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

record_store/app/controllers/records_controller.rb
class RecordsController < ApplicationController
  def show
    @record = Record.find(params[:id])
  end
  def index
    @record = Record.all
  end
  def new
     @record = Record.new
     render :new #optional
  end
    def create
    Record.create(record_params)
    redirect_to('/records')
  end
  private

  def record_params
    params.require(:record).permit(:title, :artist, :year, :cover_art, :song_count)
  end
end

record_store/app/helpers/application_helper.rb
module ApplicationHelper
end

record_store/app/helpers/records_helper.rb
module RecordsHelper
end

record_store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RecordStore</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= link_to "Make a New Record", new_record_path %>
    <%= yield %>
  </body>
</html>

record_store/app/views/records/index.html.erb
<% for record in @record %>
  <li>
   <%= link_to record.title, records_path %>
   <%= image_tag record.cover_art %>
  </li>
<% end %>

record_store/app/views/records/new.html.erb
<%= form_for @record do |f| %>
  <span>Title: </span>
  <%= f.text_field :title, required: true %><br>
  <span>Artist: </span>
  <%= f.text_field :artist, required: true %><br>
  <span>Year: </span>
  <%= f.number_field :year, required: true %><br>
  <span>Cover art: </span>
  <%= f.url_field :cover_art, required: true %><br>
  <span>Song count: </span>
  <%= f.number_field :song_count, required: true %><br>
  <%= f.submit %>
<% end %>

record_store/app/views/records/show.html.erb
title <%= @record.title %> <br>
year: <%= @record.artist%> <br>
<!-- <img src="<%= @record.cover_art %>"> -->

<%= image_tag @record.cover_art %><br>

<%= link_to "Home", records_path %>